name = "re-tui"
compatibility_date = "2026-05-10"
pages_build_output_dir = "docs"

[[d1_databases]]
binding = "RETUI_PRESETS"
database_name = "<d1-database-name>"
database_id = "<d1-database-id>"

[[r2_buckets]]
binding = "RETUI_PRESET_ASSETS"
bucket_name = "<r2-bucket-name>"
