INSERT OR REPLACE INTO presets (
  id,
  slug,
  name,
  description,
  tags,
  app_version,
  status,
  screenshot_key,
  screenshot_type,
  screenshot_size,
  preset_key,
  preset_type,
  preset_size,
  wallpaper_key,
  wallpaper_type,
  wallpaper_size,
  submitter_name,
  consent,
  created_at,
  approved_at
) VALUES (
  'northern-violet',
  'northern-violet',
  'Northern Violet',
  'Violet terminal styling with boxed launcher widgets, pale output text, and muted purple suggestion chips.',
  '["violet","terminal","dark"]',
  'v6.16.4-STABLE',
  'approved',
  'presets/northern-violet/screenshot',
  'image/png',
  3981306,
  'presets/northern-violet/preset',
  'application/zip',
  1481,
  NULL,
  NULL,
  NULL,
  'DvilSpawn',
  1,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);
